platform :ios, '8.0'
target "StudyFMDB" do
pod 'MBProgressHUD', '~> 1.0.0'
pod 'FMDB','~> 2.6.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 3.8.1'
end

